import type { PipelineContext } from '../types'
import { log, setPrUrl, setStatus } from '../logger'

export default async function openPrStep(ctx: PipelineContext): Promise<void> {
  const { job, jobId, octokit, stats, targetLanguages, githubUsername } = ctx

  const owner = job.repo_owner
  const repo = job.repo_name
  const forkOwner =
    githubUsername ?? process.env.GITHUB_BOT_USERNAME ?? 'i18n-agent-bot'
  const branchName = 'feat/i18n-lingo-dev'
  const isOwnRepo = forkOwner === owner

  const title = `🌍 Add i18n support for ${targetLanguages.length} languages (via Lingo.dev)`

  const bodyLines = [
    '## What this PR does',
    '',
    'This PR was auto-generated by Lexis.',
    '',
    '### Changes',
    '- Set up next-intl i18n routing and middleware',
    `- Extracted ${stats.stringsFound} hardcoded strings from ${stats.filesModified} files into messages/en.json`,
    `- Translated all strings into: ${targetLanguages.join(', ')}`,
    '- Added Lingo.dev configuration for automatic translations',
    '',
    '### Powered by',
    'Lingo.dev + Lexis',
  ]

  await log(jobId, {
    step: 'open-pr',
    level: 'info',
    message: isOwnRepo
      ? `Creating PR from branch ${branchName} (own repo).`
      : `Creating PR from fork ${forkOwner}/${repo}:${branchName}.`,
  })

  try {
    // Determine the head branch
    // If it's the user's own repo, head is just the branch name
    // If it's a fork, head is forkOwner:branchName
    const head = isOwnRepo ? branchName : `${forkOwner}:${branchName}`

    const pr = await octokit.pulls.create({
      owner,
      repo,
      head,
      base: 'main', // Try 'main' first, fallback to 'master' if needed
      title,
      body: bodyLines.join('\n'),
    })

    const prUrl = pr.data.html_url
    await setPrUrl(jobId, prUrl)

    await log(jobId, {
      step: 'open-pr',
      level: 'success',
      message: `PR opened: ${prUrl}`,
      data: { prUrl },
    })

    await setStatus(jobId, 'completed')
  } catch (error: any) {
    // If 'main' branch doesn't exist, try 'master'
    if (error?.status === 422 && error?.message?.includes('base')) {
      try {
        await log(jobId, {
          step: 'open-pr',
          level: 'info',
          message: `'main' branch not found, trying 'master'...`,
        })
        
        const head = isOwnRepo ? branchName : `${forkOwner}:${branchName}`
        const pr = await octokit.pulls.create({
          owner,
          repo,
          head,
          base: 'master',
          title,
          body: bodyLines.join('\n'),
        })

        const prUrl = pr.data.html_url
        await setPrUrl(jobId, prUrl)

        await log(jobId, {
          step: 'open-pr',
          level: 'success',
          message: `PR opened: ${prUrl}`,
          data: { prUrl },
        })

        await setStatus(jobId, 'completed')
        return
      } catch (retryError) {
        // Fall through to error handling
        error = retryError
      }
    }

    let message =
      error && typeof error === 'object' && 'message' in error
        ? String(error.message)
        : 'Unknown error while creating PR.'

    // Friendlier message when a PR already exists for this branch
    if (
      error?.status === 422 &&
      typeof message === 'string' &&
      message.toLowerCase().includes('pull request already exists')
    ) {
      message = `A pull request already exists for branch ${branchName} on ${owner}/${repo}.`
    }

    await log(jobId, {
      step: 'open-pr',
      level: 'error',
      message: `Failed to open PR: ${message}`,
    })

    await setStatus(jobId, 'failed', message)

    throw error
  }
}

